#!/bin/bash
# Simple script to set the correct file permissions for accessing the keyboard before opening
# VIA then setting them back once it's closed
sudo chmod a+rw /dev/hidraw1
chromium "usevia.app"
echo "test"
sudo chmod 600 /dev/hidraw1
